# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-09 01:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=50)),
                ('character_race', models.CharField(blank=True, max_length=20, null=True)),
                ('character_sex', models.CharField(blank=True, max_length=10, null=True)),
                ('character_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=50)),
                ('location_text', models.TextField(blank=True, null=True)),
                ('location_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dndb.Location')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='character_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dndb.Location'),
        ),
    ]
