# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-11 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dndb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GMInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='gm_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dndb.GMInfo'),
        ),
        migrations.AddField(
            model_name='item',
            name='gm_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dndb.GMInfo'),
        ),
        migrations.AddField(
            model_name='location',
            name='gm_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dndb.GMInfo'),
        ),
        migrations.AddField(
            model_name='task',
            name='gm_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dndb.GMInfo'),
        ),
    ]
