# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-10 20:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dndb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='character',
            old_name='character_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='character_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='character_text',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='character_race',
            new_name='race',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='character_sex',
            new_name='sex',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='location_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='location_text',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='location_location',
            new_name='parent',
        ),
        migrations.AddField(
            model_name='character',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='campaign',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='dndb.Campaign'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='campaign',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='dndb.Campaign'),
            preserve_default=False,
        ),
    ]
