# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-10 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndb', '0002_auto_20170210_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
