# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-07-02 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndb', '0002_auto_20180311_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='gm_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='gm_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='gm_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='gm_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
