# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-07-02 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dndb', '0003_auto_20180702_1344'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GMInfo',
        ),
    ]
