# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-07-02 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndb', '0004_delete_gminfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyloot',
            name='items',
            field=models.ManyToManyField(blank=True, to='dndb.Item'),
        ),
    ]
