# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-17 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dndb', '0004_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyLoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dndb.Campaign')),
            ],
        ),
    ]
