# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-22 21:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dndb', '0005_partyloot'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 2, 22, 21, 12, 33, 280314, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 2, 22, 21, 12, 40, 772845, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 2, 22, 21, 12, 51, 971971, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 2, 22, 21, 12, 57, 351008, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 2, 22, 21, 13, 2, 476649, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 2, 22, 21, 13, 7, 461882, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
