# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-07-02 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dndb', '0005_auto_20180702_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partyloot',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='partyloot',
            name='items',
        ),
        migrations.DeleteModel(
            name='PartyLoot',
        ),
    ]
