# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-23 14:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dndb', '0006_auto_20170222_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='users',
            field=models.ManyToManyField(related_name='campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='character',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='dndb.Campaign'),
        ),
        migrations.AlterField(
            model_name='character',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='dndb.Location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='dndb.Campaign'),
        ),
        migrations.AlterField(
            model_name='location',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dndb.Location'),
        ),
        migrations.AlterField(
            model_name='partyloot',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partyloot', to='dndb.Campaign'),
        ),
        migrations.AlterField(
            model_name='task',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='dndb.Campaign'),
        ),
        migrations.AlterField(
            model_name='task',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='dndb.Location'),
        ),
    ]
