# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-05 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dndb', '0011_auto_20170505_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dndb.Campaign'),
            preserve_default=False,
        ),
    ]
