# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-05 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndb', '0012_item_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyloot',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='dndb.Item'),
        ),
    ]
