# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-12 14:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dndb', '0013_auto_20170505_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 5, 12, 14, 6, 19, 991504, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 5, 12, 14, 6, 29, 722841, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
